---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: plex
spec:
  type: ClusterIP
  ports:
    - name: plex
      port: 32400
      targetPort: plex
      protocol: TCP
    - name: filebrowser
      port: 8080
      targetPort: filebrowser
      protocol: TCP
  selector:
    app.kubernetes.io/name: plex
