---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otbr-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: otbr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.services.otbr.storage_class | default "longhorn" }}
  resources:
    requests:
      storage: {{ .Values.services.otbr.storage_size | default "1Gi" }}
