---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.services.home_assistant_matter_hub.domain }}"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: "Home Automation"
    gethomepage.dev/name: "Matter Hub"
    gethomepage.dev/icon: "home-assistant"
    gethomepage.dev/description: "Home Assistant Matter bridge (dashboard)"
    gethomepage.dev/href: "https://{{ .Values.services.home_assistant_matter_hub.domain }}"
  labels:
    app.kubernetes.io/name: home-assistant-matter-hub
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.services.home_assistant_matter_hub.domain }}`)
      kind: Rule
      priority: 10
      {{- if .Values.auth_enabled }}
      middlewares:
        - name: authelia-forward-auth
          namespace: authelia
      {{- end }}
      services:
        - name: home-assistant-matter-hub
          port: {{ .Values.hamh.httpPort }}
  tls:
    secretName: {{ .Release.Name }}-tls
