global:
  domain: silverseekers.org
  cert_issuer: letsencrypt-prod

services:
  quartz:
    domain: garden.silverseekers.org
    auth_enabled: false
    repo_storage_size: 2Gi
    site_storage_size: 1Gi
    storage_class: longhorn
    couchdb_host: "http://obsidian-livesync.obsidian-livesync.svc:5984"
    couchdb_database: "obsidiannotes"

builder:
  image:
    repository: node
    tag: "20-alpine"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

nginx:
  image:
    repository: nginx
    tag: "1.27-alpine"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 128Mi

env:
  TZ: Europe/London
