apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otbr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  sources:
    - repoURL: https://github.com/HughLardner/homelab.git
      targetRevision: main
      path: kubernetes/applications/otbr
      helm:
        valueFiles:
          - $values/config/homelab.yaml
    - repoURL: https://github.com/HughLardner/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: home-automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
