---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant-matter-hub-auth
  namespace: home-assistant
spec:
  encryptedData:
    access-token: AgDIkcqVvPfXNiBDWT4FcotHVrqSzbPd4oE1EFgJHM8by7pprSZ7kaVY/NhvCStniS/vwI1eKYb8EZKUx25HTXN/03qbC2DcuCCTmRMrDnPdTKJdh7yhOkfOPLaoWDTaPG7dTuLUjrxi68R4ELziW5C+2LiqAx7oYEy1iNJtKTV7d4dqNM7JMe4JVtbrekfS/qfHiZ4Kc5NUA56nQAsESthq9p80Lk1av169kKuNsPyVOrCQNMZ69UaHgxAAbdUbNsi8CYbGFnCE7FsaBMbqWvcfysrIaL3r8c6WFrWDWcyg83TnEjQxMszpu7vM4ECcqJ2IDVoCfbZOtOQY+ONaKZ3blY65wvkezpe4ybq0t7vNBPQFZLOWYUF9ts4CLJ8g8TPV6eUmhuJlnVHCOCA9O/eP2c6sWKwgMalBYFT3AgyaxfLfNEqAB1iN27wCLMFm6gDNOoqCZ6fSWzrFiJAwWoDzgt8QUynIdjMV0ykxKCj7fqN3v8daKyD1KBnRZSGAOiVBtNmnncTk9ir8a4x4E1HdU/OZ1xSYC5fyCfUMhKR1St6skHF5Y01uurkQ/vzSMlxQFkZznLeJfSNkjc7dZ6YLbCpg5HDXApOhPRIzp0fGVHyYim6lzOyzM9U8Qr1wGH2XnG2hT17Z2Xmx4jc+OFSmXDbv1oDaQ0zjDl8IDM+2sgcEAeUoKhj+vI/92PH8+/yCFb+MtBPae4m0Shz3EjBP8KQkffPIvEfQtZUp2W7bGIKBCMn7elr394UzZawiz2gbaHRDtvb0zNM+IINMGoMHbXIbNvNE2r4faGlYh+oYiZPqwVcMphpoVMpE9IsUNdV+wm+2dHtGm9gNw3QKZ3iY86fY1PIJTtt9d1kQiT1Oskqu9Ab/0/Uf11JMVrDDOBv9kYzTWjWTPpHPYLO7BhajQr1ws7wWC7hWGCal0eG2nwi4aJOZCgY=
  template:
    metadata:
      name: home-assistant-matter-hub-auth
      namespace: home-assistant
