{
 "title": "Unified Logs",
 "description": "Unified log exploration across Kubernetes workloads and external device syslog streams in Loki.",
 "tags": [
  "loki",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values({namespace=~\"$namespace\"}, pod)"
   },
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values({job=~\"$job\"}, device)"
   },
   {
    "name": "source_host",
    "label": "Source Host",
    "query": "label_values({job=~\"$job\", device=~\"$device\"}, source_host)"
   },
   {
    "name": "appname",
    "label": "Appname",
    "query": "label_values({job=~\"$job\", device=~\"$device\"}, appname)"
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes Log Lines ($__range)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Device Log Lines ($__range)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", device=~\"$device\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Kubernetes Errors ($__range)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\"} |~ \"(?i)error|exception|fail\" [$__range]))"
    }
   ]
  },
  {
   "title": "Device Errors and Warnings ($__range)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\", device=~\"$device\"} |~ \"(?i)error|warn|fail\" [$__range]))"
    }
   ]
  },
  {
   "title": "Kubernetes Log Volume by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (count_over_time({namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Device Log Volume by Source Host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source_host) (count_over_time({job=~\"$job\", device=~\"$device\", source_host=~\"$source_host\"}[$__interval]))",
     "legendFormat": "{{source_host}}"
    }
   ]
  },
  {
   "title": "Kubernetes Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\"} |= \"$search\""
    }
   ]
  },
  {
   "title": "Device Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "{job=~\"$job\", device=~\"$device\", source_host=~\"$source_host\", appname=~\"$appname\"} |= \"$search\""
    }
   ]
  }
 ]
}