---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: zigbee2mqtt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.services.zigbee2mqtt.storage_class | default "longhorn" }}
  resources:
    requests:
      storage: {{ .Values.services.zigbee2mqtt.storage_size | default "2Gi" }}
