---
apiVersion: v1
kind: Service
metadata:
  name: forgejo
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: forgejo
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Forgejo
    gethomepage.dev/description: Self-Hosted Git Server
    gethomepage.dev/group: Applications
    gethomepage.dev/icon: forgejo
    gethomepage.dev/href: "https://{{ .Values.services.forgejo.domain }}"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: ssh
      protocol: TCP
  selector:
    app.kubernetes.io/name: forgejo
