---
apiVersion: v1
kind: Service
metadata:
  name: forgejo
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: forgejo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: ssh
      protocol: TCP
  selector:
    app.kubernetes.io/name: forgejo
