auth_enabled: true

priorityClassName: homelab-standard

image:
  repository: ghcr.io/koenkk/zigbee2mqtt
  tag: "2.1.1"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  TZ: Europe/London
  ZIGBEE2MQTT_DATA: /data
  ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
  ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: zigbee2mqtt
  ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
  ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: "8080"
  ZIGBEE2MQTT_CONFIG_FRONTEND_HOST: "0.0.0.0"
  ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
  ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info
  ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
  ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
