---
apiVersion: v1
kind: Service
metadata:
  name: quartz-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: quartz
    app.kubernetes.io/component: nginx
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: quartz
    app.kubernetes.io/component: nginx
