---
apiVersion: v1
kind: Service
metadata:
  name: quartz-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: quartz
    app.kubernetes.io/component: nginx
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Digital Garden
    gethomepage.dev/description: Quartz Digital Garden
    gethomepage.dev/group: Applications
    gethomepage.dev/icon: mdi-book-open-page-variant
    gethomepage.dev/href: "https://{{ .Values.services.quartz.domain }}"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: quartz
    app.kubernetes.io/component: nginx
