---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-livesync-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: obsidian-livesync
    app.kubernetes.io/component: couchdb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.services.obsidian_livesync.storage_class | default "longhorn" }}
  resources:
    requests:
      storage: {{ .Values.services.obsidian_livesync.storage_size | default "5Gi" }}
