---
apiVersion: v1
kind: Service
metadata:
  name: obsidian-livesync
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: obsidian-livesync
    app.kubernetes.io/component: couchdb
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.obsidian_livesync.couchdb_port | default 5984 }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: obsidian-livesync
    app.kubernetes.io/component: couchdb
