# Default values for headlamp-ingress chart
# These are overridden by config/homelab.yaml when deploying

global:
  domain: silverseekers.org
  cert_issuer: letsencrypt-prod

priorityClassName: homelab-interactive

services:
  headlamp:
    domain: headlamp.silverseekers.org
    auth_enabled: true
