---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: matter-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.services.python_matter_server.storage_class | default .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.services.python_matter_server.storage_size | default .Values.persistence.size }}
