---
apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: matter-server
    app.kubernetes.io/component: matter-protocol
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    app.kubernetes.io/name: matter-server
