---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-ha-webhook
  namespace: monitoring
spec:
  encryptedData:
    webhookUrl: AgDDz+0ln+CzIEGOwGbUrgOI0QC5jmJW8rZijYZ8fC58T4RmnoAkbh06KceDYBJUY4vfnv2NdJgPZhaZmCvwzYNIplFfBJdPthUrii62mbgsIWMlunUsf7ziYz0oT3sjaoIZeai0Uas5K+QRuol8dVJoi1P9KRB5kXi/4CjnuRClXS5jX/8Ax94cU/0dyRhXbiiJYAiFS1TWkGf3y9Z+QIeb6BthHEjCbRdRsJrZ34ADvNVXWJFggqHlx4NhSN6JEKNrtGA+9CGP5k3cGi/UqrRfuyXubcDIZP/SbyAQOR8nvbT0K8k9QjQM6BVVDPE2uOgO3ZX0+HSVziW/jwlfAEJ9gTq0nQUkwXNHbwfogISGBG60KySJ9Sb/TiAakC0ZS1N3D8xpLOHZdM7Y2NxGfT2RDnrE0MO7oQaXtdREz9oBjyZBFzD6G1aK7LLYSChz2pW8iRbWLLRSf17gyonBijuh4RkT8bw0wLpOy3SLLJ1T7999OG+u+Rq6cvXwQVgOu7YS/1EuwXQsIZZLEVVjHanktMJrvi2lmBO2W0kJuEypdFANNA9Svcmw7/49ZTg/sfNTG4kf4nqCvB2OgMD2nUgNz2j1AyQkI91iiFGF7ZBKY3fZ/wuzMuLU4VDAIQqcTM+YKV3PMug/q2uLB0Ml1b9GpKZybVvQDh3we7lNqi6ZOiaOsDvXtOwFkXaH34KB7ozx7yXGMqsZq1+iwbApz+5u8cHRdhpwc4tPbrdRZ3RKAr1XJlBL8OoQy2zyLNqS05Aco9rBTwRZcxU2UF5nGsK6dNoMqfkjhT+rrw==
  template:
    metadata:
      name: alertmanager-ha-webhook
      namespace: monitoring
